In [6]:
import pandas as pd 
import numpy as np

In [7]:
cols_needed = ['loan_amnt','term','int_rate','installment','grade','sub_grade',
               'purpose','issue_d','emp_length','home_ownership','annual_inc',
               'verification_status','addr_state','dti','earliest_cr_line',
               'fico_range_low','fico_range_high','open_acc','pub_rec',
               'revol_bal','revol_util','total_acc','loan_status']

In [8]:
fin = pd.read_csv("../Data/accepted_2007_to_2018Q4.csv.gz", compression='gzip', usecols=cols_needed)

In [9]:
fin.shape

(2260701, 23)

In [10]:
fin.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,fico_range_low,fico_range_high,open_acc,pub_rec,revol_bal,revol_util,total_acc
count,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,2.258957e+06,2.260668e+06,2.260668e+06,2.260639e+06,2.260639e+06,2.260668e+06,2.258866e+06,2.260639e+06
mean,1.504693e+04,1.309283e+01,4.458068e+02,7.799243e+04,1.882420e+01,6.985882e+02,7.025884e+02,1.161240e+01,1.975278e-01,1.665846e+04,5.033770e+01,2.416255e+01
std,9.190245e+03,4.832138e+00,2.671735e+02,1.126962e+05,1.418333e+01,3.301038e+01,3.301124e+01,5.640861e+00,5.705150e-01,2.294831e+04,2.471307e+01,1.198753e+01
min,5.000000e+02,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,6.100000e+02,6.140000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,1.189000e+01,6.750000e+02,6.790000e+02,8.000000e+00,0.000000e+00,5.950000e+03,3.150000e+01,1.500000e+01
50%,1.290000e+04,1.262000e+01,3.779900e+02,6.500000e+04,1.784000e+01,6.900000e+02,6.940000e+02,1.100000e+01,0.000000e+00,1.132400e+04,5.030000e+01,2.200000e+01
75%,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,2.449000e+01,7.150000e+02,7.190000e+02,1.400000e+01,0.000000e+00,2.024600e+04,6.940000e+01,3.100000e+01
max,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,8.450000e+02,8.500000e+02,1.010000e+02,8.600000e+01,2.904836e+06,8.923000e+02,1.760000e+02

In [11]:
fin.info()

<class 'pandas.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 23 columns):
 #   Column               Dtype
---  ------               -----
 0   loan_amnt            float64
 1   term                 str
 2   int_rate             float64
 3   installment          float64
 4   grade                str
 5   sub_grade            str
 6   emp_length           str
 7   home_ownership       str
 8   annual_inc           float64
 9   verification_status  str
 10  issue_d              str
 11  loan_status          str
 12  purpose              str
 13  addr_state           str
 14  dti                  float64
 15  earliest_cr_line     str
 16  fico_range_low       float64
 17  fico_range_high      float64
 18  open_acc             float64
 19  pub_rec              float64
 20  revol_bal            float64
 21  revol_util           float64
 22  total_acc            float64
dtypes: float64(12), str(11)
memory usage: 396.7 MB

In [12]:
fin.isnull().sum()

loan_amnt                  33
term                       33
int_rate                   33
installment                33
grade                      33
sub_grade                  33
emp_length             146940
home_ownership             33
annual_inc                 37
verification_status        33
issue_d                    33
loan_status                33
purpose                    33
addr_state                 33
dti                      1744
earliest_cr_line           62
fico_range_low             33
fico_range_high            33
open_acc                   62
pub_rec                    62
revol_bal                  33
revol_util               1835
total_acc                  62
dtype: int64

In [13]:
df = fin.copy()

In [14]:
df.shape

(2260701, 23)

In [15]:
fin[fin.duplicated()]

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,...,addr_state,dti,earliest_cr_line,fico_range_low,fico_range_high,open_acc,pub_rec,revol_bal,revol_util,total_acc
421096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
749520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
749521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
983169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
983170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1352689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1352690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1611877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1611878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1651665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1654415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1654416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1751196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1751197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1939379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1939380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2038501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2038502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2157151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2157152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df = df.drop_duplicates()

In [17]:
df.shape

(2260669, 23)

In [18]:
df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,...,addr_state,dti,earliest_cr_line,fico_range_low,fico_range_high,open_acc,pub_rec,revol_bal,revol_util,total_acc
0,3600.0,36 months,13.99,123.03,C,C4,10+ years,MORTGAGE,55000.0,Not Verified,...,PA,5.91,Aug-2003,675.0,679.0,7.0,0.0,2765.0,29.7,13.0
1,24700.0,36 months,11.99,820.28,C,C1,10+ years,MORTGAGE,65000.0,Not Verified,...,SD,16.06,Dec-1999,715.0,719.0,22.0,0.0,21470.0,19.2,38.0
2,20000.0,60 months,10.78,432.66,B,B4,10+ years,MORTGAGE,63000.0,Not Verified,...,IL,10.78,Aug-2000,695.0,699.0,6.0,0.0,7869.0,56.2,18.0
3,35000.0,60 months,14.85,829.90,C,C5,10+ years,MORTGAGE,110000.0,Source Verified,...,NJ,17.06,Sep-2008,785.0,789.0,13.0,0.0,7802.0,11.6,17.0
4,10400.0,60 months,22.45,289.91,F,F1,3 years,MORTGAGE,104433.0,Source Verified,...,PA,25.37,Jun-1998,695.0,699.0,12.0,0.0,21929.0,64.5,35.0

In [19]:
df.dropna(subset=['loan_amnt'],inplace= True)

In [20]:
df.isnull().sum()

loan_amnt                   0
term                        0
int_rate                    0
installment                 0
grade                       0
sub_grade                   0
emp_length             146907
home_ownership              0
annual_inc                  4
verification_status         0
issue_d                     0
loan_status                 0
purpose                     0
addr_state                  0
dti                      1711
earliest_cr_line           29
fico_range_low              0
fico_range_high             0
open_acc                   29
pub_rec                    29
revol_bal                   0
revol_util               1802
total_acc                  29
dtype: int64

In [21]:
# replacing 0 in place of nulls in numerical columns to fill the data
df['pub_rec']= df['pub_rec'].fillna(0)
df['open_acc']= df['open_acc'].fillna(0)
df['total_acc']= df['total_acc'].fillna(0)

In [22]:
# median value in null value holders
df['annual_inc'] = df['annual_inc'].fillna(df['annual_inc'].median())
df['dti'] = df['dti'].fillna(df['dti'].median())
df['revol_util'] = df['revol_util'].fillna(df['revol_util'].median())

#median fill up in emp_length series
df['emp_length']= df['emp_length'].fillna('Unknown')

In [23]:
# Drop only the null rows for these two columns
df.dropna(subset=['issue_d', 'earliest_cr_line'], inplace=True)

In [24]:
df.isnull().sum()

loan_amnt              0
term                   0
int_rate               0
installment            0
grade                  0
sub_grade              0
emp_length             0
home_ownership         0
annual_inc             0
verification_status    0
issue_d                0
loan_status            0
purpose                0
addr_state             0
dti                    0
earliest_cr_line       0
fico_range_low         0
fico_range_high        0
open_acc               0
pub_rec                0
revol_bal              0
revol_util             0
total_acc              0
dtype: int64

In [25]:
df.shape

(2260639, 23)

In [26]:
df.columns

Index(['loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'purpose', 'addr_state', 'dti',
       'earliest_cr_line', 'fico_range_low', 'fico_range_high', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc'],
      dtype='str')

In [36]:
df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,...,addr_state,dti,earliest_cr_line,fico_range_low,fico_range_high,open_acc,pub_rec,revol_bal,revol_util,total_acc
0,3600.0,36,13.99,123.03,C,C4,10+ years,MORTGAGE,55000.0,Not Verified,...,PA,5.91,2003-08-01,675.0,679.0,7.0,0.0,2765.0,29.7,13.0
1,24700.0,36,11.99,820.28,C,C1,10+ years,MORTGAGE,65000.0,Not Verified,...,SD,16.06,1999-12-01,715.0,719.0,22.0,0.0,21470.0,19.2,38.0
2,20000.0,60,10.78,432.66,B,B4,10+ years,MORTGAGE,63000.0,Not Verified,...,IL,10.78,2000-08-01,695.0,699.0,6.0,0.0,7869.0,56.2,18.0
3,35000.0,60,14.85,829.90,C,C5,10+ years,MORTGAGE,110000.0,Source Verified,...,NJ,17.06,2008-09-01,785.0,789.0,13.0,0.0,7802.0,11.6,17.0
4,10400.0,60,22.45,289.91,F,F1,3 years,MORTGAGE,104433.0,Source Verified,...,PA,25.37,1998-06-01,695.0,699.0,12.0,0.0,21929.0,64.5,35.0

In [27]:
df[[ 'issue_d', 'loan_status', 'purpose']].sample(10)

          issue_d loan_status             purpose
1177355  Oct-2014  Fully Paid    home_improvement
1686037  Mar-2017     Current  debt_consolidation
727976   Apr-2016  Fully Paid  debt_consolidation
1929311  Apr-2012  Fully Paid         credit_card
574998   Aug-2017     Current  debt_consolidation
1637679  Sep-2010  Fully Paid    renewable_energy
912935   Jun-2017     Current  debt_consolidation
74624    Nov-2015     Current               other
1646293  Oct-2009  Fully Paid  debt_consolidation
1236922  Jul-2014  Fully Paid  debt_consolidation

In [28]:
df[['revol_bal','issue_d', 'loan_status', 'purpose']].info()

<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   revol_bal    float64
 1   issue_d      str
 2   loan_status  str
 3   purpose      str
dtypes: float64(1), str(3)
memory usage: 86.2 MB

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 23 columns):
 #   Column               Dtype
---  ------               -----
 0   loan_amnt            float64
 1   term                 str
 2   int_rate             float64
 3   installment          float64
 4   grade                str
 5   sub_grade            str
 6   emp_length           str
 7   home_ownership       str
 8   annual_inc           float64
 9   verification_status  str
 10  issue_d              str
 11  loan_status          str
 12  purpose              str
 13  addr_state           str
 14  dti                  float64
 15  earliest_cr_line     str
 16  fico_range_low       float64
 17  fico_range_high      float64
 18  open_acc             float64
 19  pub_rec              float64
 20  revol_bal            float64
 21  revol_util           float64
 22  total_acc            float64
dtypes: float64(12), str(11)
memory usage: 413.9 MB

In [30]:
df['int_rate'].astype('float16')
df['issue_d'] = pd.to_datetime(df['issue_d'],errors= 'coerce')
df['earliest_cr_line'] = pd.to_datetime(df['earliest_cr_line'], errors= 'coerce')
df['term'] = (df['term'].str.replace(' months','').str.strip()).astype('int16')

C:\Users\aalgo\AppData\Local\Temp\ipykernel_7840\807495525.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['issue_d'] = pd.to_datetime(df['issue_d'],errors= 'coerce')
C:\Users\aalgo\AppData\Local\Temp\ipykernel_7840\807495525.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['earliest_cr_line'] = pd.to_datetime(df['earliest_cr_line'], errors= 'coerce')

In [31]:
df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,...,addr_state,dti,earliest_cr_line,fico_range_low,fico_range_high,open_acc,pub_rec,revol_bal,revol_util,total_acc
0,3600.0,36,13.99,123.03,C,C4,10+ years,MORTGAGE,55000.0,Not Verified,...,PA,5.91,2003-08-01,675.0,679.0,7.0,0.0,2765.0,29.7,13.0
1,24700.0,36,11.99,820.28,C,C1,10+ years,MORTGAGE,65000.0,Not Verified,...,SD,16.06,1999-12-01,715.0,719.0,22.0,0.0,21470.0,19.2,38.0
2,20000.0,60,10.78,432.66,B,B4,10+ years,MORTGAGE,63000.0,Not Verified,...,IL,10.78,2000-08-01,695.0,699.0,6.0,0.0,7869.0,56.2,18.0
3,35000.0,60,14.85,829.90,C,C5,10+ years,MORTGAGE,110000.0,Source Verified,...,NJ,17.06,2008-09-01,785.0,789.0,13.0,0.0,7802.0,11.6,17.0
4,10400.0,60,22.45,289.91,F,F1,3 years,MORTGAGE,104433.0,Source Verified,...,PA,25.37,1998-06-01,695.0,699.0,12.0,0.0,21929.0,64.5,35.0

In [32]:
df.info()

<class 'pandas.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 23 columns):
 #   Column               Dtype
---  ------               -----
 0   loan_amnt            float64
 1   term                 int16
 2   int_rate             float64
 3   installment          float64
 4   grade                str
 5   sub_grade            str
 6   emp_length           str
 7   home_ownership       str
 8   annual_inc           float64
 9   verification_status  str
 10  issue_d              datetime64[us]
 11  loan_status          str
 12  purpose              str
 13  addr_state           str
 14  dti                  float64
 15  earliest_cr_line     datetime64[us]
 16  fico_range_low       float64
 17  fico_range_high      float64
 18  open_acc             float64
 19  pub_rec              float64
 20  revol_bal            float64
 21  revol_util           float64
 22  total_acc            float64
dtypes: datetime64[us](2), float64(12), int16(1), str(8)
memory usage: 401.0 MB

In [33]:
# checking if any Datetime type is not occured and returned NaN value 
df.isnull().sum()

loan_amnt              0
term                   0
int_rate               0
installment            0
grade                  0
sub_grade              0
emp_length             0
home_ownership         0
annual_inc             0
verification_status    0
issue_d                0
loan_status            0
purpose                0
addr_state             0
dti                    0
earliest_cr_line       0
fico_range_low         0
fico_range_high        0
open_acc               0
pub_rec                0
revol_bal              0
revol_util             0
total_acc              0
dtype: int64

In [35]:
pd = df.to_csv('Lending_loan_cleaned.csv',index = False)